--- 
- 
  connection: local
  gather_facts: false
  hosts: all
  vars:
    project_dir: /var/lib/jenkins/workspace/terraform-ansible
  name: "Execute terraform plan"
  tasks: 
    - 
      terraform: 
        project_path: '{{ project_dir }}'
        state: planned
        plan_file: ""
        variables_file: "/var/lib/jenkins/workspace/terraform-ansible/terraform.tfvars"
        variables:
          var_project_region: "us-east4"
        force_init: true
        backend_config:
          bucket: "tf-state-store-backend"
          prefix: "tf-state-store"
          credentials: "/home/karthick/credentials/gcs-e10aec265420.json"

